# Generated by Django 5.0.1 on 2024-07-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogscomment',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
    ]
