# Generated by Django 5.0.1 on 2024-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_id_deleted_blogscomment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='comment_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
