# Generated by Django 5.0.1 on 2024-03-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
    ]
